---
title: "R Notebook"
output: html_notebook
---

Follow on from the MAP_file_pipeline.Rmd analysis.

```{r}
library(tidyverse)
source("MAP_functions.R")
```


```{r}
list_of_87 <- read.delim("list_87_strains.txt", header = F)
MAP_minor_alleles_df <- read.delim("~/GitHub/Ct_MAP_analysis/MAP_minor_alleles_df2.tsv") %>%
  mutate(strain = sub("-WGS","",strain)) %>%
  mutate(strain = sub("Rs","R",strain)) %>%
  mutate(strain = sub("Vs","V",strain)) %>%
  mutate(subject = sub("C|R|V","",strain)) %>%
  mutate(site = substr(strain,nchar(strain),nchar(strain))) %>%
  filter(strain %in% list_of_87$V1)

```

```{r}
MAP_minor_alleles_df %>%
  group_by(strain) %>%
  tally
```

```{r}
Pos_count <- MAP_minor_alleles_df %>%
  group_by(Position) %>%
  tally
write_tsv(Pos_count,"Pos_count.tsv")
```
`


```{r}
Pos_count %>%
  filter(n < 11) %>%
  tally()
```


```{r}
Pos_count %>%
  mutate(rare = ifelse(n < 4,"yes","no")) %>%
  ggplot(aes(x = n, fill = rare)) + 
    geom_histogram(binwidth=1) +
    ylab("Number of iSNPs") +
    xlab("Number of strains") +
    ggtitle("Figure_Y1 - How many strains were each iSNP found in?") +
    scale_fill_manual(values = c("gainsboro","red")) +
    geom_vline(xintercept = 3, color = "red", linetype = "dotted") +
    theme_bw()
```
# look at posiiotns of common SNPs

```{r}
ggplot(filter(Pos_count,n > 10),aes(Position)) + 
    geom_histogram(binwidth=10000) +
    ggtitle("Minor alleles across the genome") +
    xlim(1,1042519) +
    ylim(0,5) +
    theme_bw()
```



# look at position by subject

```{r}
ggplot(Pos_count,aes(Position)) + 
    geom_histogram(binwidth=10000) +
    ggtitle("Minor alleles across the genome") +
    xlim(1,1042519) +
    ylim(0,450) +
    theme_bw()
```


```{r}
ggplot(filter(MAP_minor_alleles_df,strain == "1176V"),aes(Position)) + 
  geom_histogram(binwidth=10000) +
    ggtitle("1176V Minor alleles across the genome") +
    xlim(1,1042519) +
    ylim(0,450) +
    theme_bw()
```

```{r}
ggplot(filter(MAP_minor_alleles_df,strain == "32V"),aes(Position)) + 
  geom_histogram(binwidth=10000) +
    ggtitle("32V Minor alleles across the genome") +
    xlim(1,1042519) +
    ylim(0,450) +
    theme_bw()
```


```{r}
ggplot(filter(MAP_minor_alleles_df,strain == "1182R"),aes(Position)) + 
  geom_histogram(binwidth=10000) +
    ggtitle("1182R Minor alleles across the genome") +
    xlim(1,1042519) +
    ylim(0,450) +
    theme_bw()
```


```{r}
ggplot(filter(MAP_minor_alleles_df,strain == "1078V"),aes(Position)) + 
  geom_histogram(binwidth=10000) +
    ggtitle("1078V Minor alleles across the genome") +
    xlim(1,1042519) +
    ylim(0,450) +
    theme_bw()
```


```{r}
ggplot(filter(MAP_minor_alleles_df,strain == "1079R"),aes(Position)) + 
  geom_histogram(binwidth=10000) +
    ggtitle("1079R Minor alleles across the genome") +
    xlim(1,1042519) +
    ylim(0,450) +
    theme_bw()
```


```{r}
ggplot(filter(MAP_minor_alleles_df,strain == "1176R"),aes(Position)) + 
  geom_histogram(binwidth=10000) +
    ggtitle("1176R Minor alleles across the genome") +
    xlim(1,1042519) +
    ylim(0,450) +
    theme_bw()
```

