---
title: "make_iSNP_table.Rmd"
output: html_document
---

```{r}
library(tidyverse)
```


```{r}
res_files <- list.files("./iSNP_analysis_table/",full.names = T, pattern = "iSNP*")
res_table <- read.delim(res_files[1])
for (i in 2:length(res_files)){
  temp_df <- read.delim(res_files[i])
  res_table <- bind_rows(res_table,temp_df)
}
```

```{r}
write_tsv(res_table,"./iSNP_analysis_table/all_results_table.tsv")
```

### compare to raw data

```{r}
grand_summary <- read.delim("./2021_08_24-Grand_Summary - MAP_analysis_summary.tsv")
```

```{r}
mean_doc <- grand_summary %>% 
  select(Sample,Mean.depth.of.coverage)
```



```{r}
RI_SNPs <- res_table %>% 
  select(subject_name,RonlyRI,ConlyRI,VonlyRI) %>%
  gather("site","SNPs",-subject_name) %>%
  mutate(Sample = case_when(site == "RonlyRI" ~ paste0(subject_name,"R"),
                                site == "ConlyRI" ~ paste0(subject_name,"C"),
                                site == "VonlyRI" ~ paste0(subject_name,"V")
                                )) %>% 
  inner_join(.,mean_doc, by = "Sample")
```

```{r}
ggplot(RI_SNPs,aes(x=Mean.depth.of.coverage,y=SNPs)) +
  geom_point()+
  theme_bw() +
  ggtitle("Numbers of rare intermediate SNPs versus sample depth of coverage")
```


```{r}
F_SNPs <- res_table %>% 
  select(subject_name,RonlyF,ConlyF,VonlyF) %>%
  gather("site","SNPs",-subject_name) %>%
  mutate(Sample = case_when(site == "RonlyF" ~ paste0(subject_name,"R"),
                                site == "ConlyF" ~ paste0(subject_name,"C"),
                                site == "VonlyF" ~ paste0(subject_name,"V")
                                )) %>% 
  inner_join(.,mean_doc, by = "Sample")
```


```{r}
ggplot(F_SNPs,aes(x=Mean.depth.of.coverage,y=SNPs)) +
  geom_point()+
  theme_bw() +
  ggtitle("Numbers of rare intermediate SNPs versus sample depth of coverage")
```

